export const ALL_SERVICES = [
  "24 Hour Locksmith Service",
  "Emergency Locksmith Service",
  "Locksmith Services",
  "Local Locksmith Service",
  "Reliable Locksmith Service",
  "Professional Locksmith Service",
  "Residential Locksmith Service",
  "Commercial Locksmith Service",
  "Automotive Locksmith Service",
  "Key Duplication Service",
  "Lock Installation Service",
  "Lock Repair Service",
  "Rekeying Service",
  "Master Key System Service",
  "High-Security Lock Service",
  "Safe Opening Service",
  "Safe Installation Service",
  "Lockout Service",
  "Broken Key Extraction Service",
  "Keyless Entry System Service",
  "Access Control System Service",
  "Security System Installation",
  "Panic Bar Installation",
  "Door Closer Installation",
  "Electronic Lock Service",
  "Biometric Lock Service",
  "Garage Door Lock Service",
  "File Cabinet Lock Service",
  "Mailbox Lock Service",
  "Window Lock Service",
  "Sliding Door Lock Service",
  "Emergency Car Unlocking",
  "Trunk Unlocking Service",
  "Transponder Key Programming",
  "Smart Lock Installation",
  "Digital Lock Service",
  "Intercom System Installation",
  "Gate Lock Service",
  "Fence Lock Service",
  "Emergency Exit Device Installation",
  "Push Bar Installation",
  "Key Fob Replacement",
  "Remote Key Programming",
  "Ignition Repair Service",
  "Ignition Replacement Service",
  "Car Key Replacement",
  "High-Security Key Duplication",
  "Key Card System Service",
  "Door Lock Replacement",
  "Home Security Audit",
  "Lock Maintenance Service",
  "Padlock Service",
  "Bump Key Protection Service",
  "Lock Cylinder Replacement",
  "Lock Adjustment Service",
  "Security Bar Installation",
  "Patio Door Lock Service",
  "Storm Door Lock Service",
  "Digital Safe Service",
  "Vault Opening Service",
  "Vault Installation Service",
  "Electromagnetic Lock Service",
  "Electric Strike Installation",
  "Magnetic Lock Service",
  "Deadbolt Installation",
  "Deadbolt Repair",
  "Combination Lock Service",
  "Cam Lock Service",
  "Cabinet Lock Service",
  "Desk Lock Service",
  "High-Security Door Installation",
  "Lock Pick Service",
  "Eviction Locksmith Service",
  "Foreclosure Locksmith Service",
  "Eviction Lockout Service",
  "Fingerprint Lock Service",
  "Proximity Card System Service",
  "CCTV Installation",
  "Alarm System Installation",
  "Security Consultation",
  "Buzzer System Installation",
  "Emergency Lock Rekeying",
  "High-Security Lock Installation",
  "School Lockdown System Service",
  "Hospital Lock System Service",
  "Hotel Lock System Service",
  "Motel Lock System Service",
  "Apartment Lock System Service",
  "Condo Lock System Service",
  "Industrial Locksmith Service",
  "Factory Lock System Service",
  "Warehouse Lock System Service",
  "Retail Store Lock System Service",
  "Restaurant Lock System Service",
  "Office Lock System Service",
  "Building Lock System Service",
  "Facility Lock System Service",
  "Church Lock System Service",
  "Library Lock System Service",
  "Museum Lock System Service",
  "University Lock System Service",
  "School Lock System Service",
];
export const LOCATION = "west brompton";
